DROP TABLE IF EXISTS "Contact"
--NST
DROP TABLE IF EXISTS "ContactList"
--NST
DROP TABLE IF EXISTS "Pictogram"
--NST
DROP TABLE IF EXISTS "Category"
--NST
DROP TABLE IF EXISTS "MajorCategory"
--NST
DROP TABLE IF EXISTS "WardedPictogram"
--NST
DROP TABLE IF EXISTS "QuickMessage"
--NST
DROP TABLE IF EXISTS "QMMessage"
--NST
DROP TABLE IF EXISTS "User"
--NST
DROP TABLE IF EXISTS "Room"
--NST
DROP TABLE IF EXISTS "Message"
--NST
DROP TABLE IF EXISTS "Conversation"
--NST
DROP TABLE IF EXISTS "Settings"